### ISSUE TITLE
New build needed

### ISSUE THREAD

**Issue by emk** [rustasync/route-recognizer#11]
Hello, I'm trying to fix iron/router to get the Heroku example program working again, and it looks like the crates.io version of route-recognizer is out of date. Could we please have a new package? :-)

(Also, is there a better stack to use than iron, for demo purposes? conduit looks interesting but there are no docs that I can find yet.)

**Comment by Nemo157** [comment]
There have been a few releases since this was opened, I assume it's been sorted by now :)
